version: "2"

services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: anafarg
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/datasources:/etc/grafana/provisioning/datasources"

  mysql:
    image: mysql
    container_name: "db"
    environment:
      MYSQL_ROOT_PASSWORD: "fourWinsPwd"
    ports:
            - "3306:3306"
